server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8


spring:
  application:
    name: abtest

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: NEVER
    druid:
      validation-query: select 1 test
      url: jdbc:mysql://localhost:3306/abtest?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 20
      min-idle: 5
  redis:
    database: 2
#    host: 192.168.2.242
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-idle: 5
        min-idle: 0
        max-active: 8
        max-wait: 1

mybatis:
  config-location: classpath:mybatis/mybatis_configure.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

async:
  worker:
    thread:
      core_pool_size: 5
      max_pool_size: 5
      queue_capacity: 99999
      name:
        prefix: async-service-
logging:
  file:
    path: log